-- -------------------------------------------------------------
--
-- Module: filter
-- Generated by MATLAB(R) 9.10 and Filter Design HDL Coder 3.1.9.
-- Generated on: 2022-03-29 16:55:30
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- ResetAssertedLevel: Active-low
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filter IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(15 DOWNTO 0); -- sfix16
         filter_out                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32
         );

END filter;


----------------------------------------------------------------
--Module Architecture: filter
----------------------------------------------------------------
ARCHITECTURE rtl OF filter IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(15 DOWNTO 0); -- sfix16
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(1074, 16); -- sfix16_En20
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(1108, 16); -- sfix16_En20
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(1168, 16); -- sfix16_En20
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(1255, 16); -- sfix16_En20
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(1370, 16); -- sfix16_En20
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(1515, 16); -- sfix16_En20
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(1690, 16); -- sfix16_En20
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(1896, 16); -- sfix16_En20
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(2133, 16); -- sfix16_En20
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(2401, 16); -- sfix16_En20
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(2700, 16); -- sfix16_En20
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(3030, 16); -- sfix16_En20
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(3391, 16); -- sfix16_En20
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(3783, 16); -- sfix16_En20
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(4203, 16); -- sfix16_En20
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(4652, 16); -- sfix16_En20
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(5127, 16); -- sfix16_En20
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(5629, 16); -- sfix16_En20
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(6154, 16); -- sfix16_En20
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(6702, 16); -- sfix16_En20
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(7269, 16); -- sfix16_En20
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(7855, 16); -- sfix16_En20
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(8457, 16); -- sfix16_En20
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(9073, 16); -- sfix16_En20
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(9699, 16); -- sfix16_En20
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(10334, 16); -- sfix16_En20
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(10974, 16); -- sfix16_En20
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(11617, 16); -- sfix16_En20
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(12260, 16); -- sfix16_En20
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(12900, 16); -- sfix16_En20
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(13534, 16); -- sfix16_En20
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(14159, 16); -- sfix16_En20
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(14772, 16); -- sfix16_En20
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(15370, 16); -- sfix16_En20
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(15950, 16); -- sfix16_En20
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(16509, 16); -- sfix16_En20
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(17046, 16); -- sfix16_En20
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(17556, 16); -- sfix16_En20
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(18038, 16); -- sfix16_En20
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(18488, 16); -- sfix16_En20
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(18906, 16); -- sfix16_En20
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(19288, 16); -- sfix16_En20
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(19632, 16); -- sfix16_En20
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(19938, 16); -- sfix16_En20
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(20203, 16); -- sfix16_En20
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(20426, 16); -- sfix16_En20
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(20606, 16); -- sfix16_En20
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(20741, 16); -- sfix16_En20
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(20832, 16); -- sfix16_En20
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(20878, 16); -- sfix16_En20
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(20878, 16); -- sfix16_En20
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(20832, 16); -- sfix16_En20
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(20741, 16); -- sfix16_En20
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(20606, 16); -- sfix16_En20
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(20426, 16); -- sfix16_En20
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(20203, 16); -- sfix16_En20
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(19938, 16); -- sfix16_En20
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(19632, 16); -- sfix16_En20
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(19288, 16); -- sfix16_En20
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(18906, 16); -- sfix16_En20
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(18488, 16); -- sfix16_En20
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(18038, 16); -- sfix16_En20
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(17556, 16); -- sfix16_En20
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(17046, 16); -- sfix16_En20
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(16509, 16); -- sfix16_En20
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(15950, 16); -- sfix16_En20
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(15370, 16); -- sfix16_En20
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(14772, 16); -- sfix16_En20
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(14159, 16); -- sfix16_En20
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(13534, 16); -- sfix16_En20
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(12900, 16); -- sfix16_En20
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(12260, 16); -- sfix16_En20
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(11617, 16); -- sfix16_En20
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(10974, 16); -- sfix16_En20
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(10334, 16); -- sfix16_En20
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(9699, 16); -- sfix16_En20
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(9073, 16); -- sfix16_En20
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(8457, 16); -- sfix16_En20
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(7855, 16); -- sfix16_En20
  CONSTANT coeff80                        : signed(15 DOWNTO 0) := to_signed(7269, 16); -- sfix16_En20
  CONSTANT coeff81                        : signed(15 DOWNTO 0) := to_signed(6702, 16); -- sfix16_En20
  CONSTANT coeff82                        : signed(15 DOWNTO 0) := to_signed(6154, 16); -- sfix16_En20
  CONSTANT coeff83                        : signed(15 DOWNTO 0) := to_signed(5629, 16); -- sfix16_En20
  CONSTANT coeff84                        : signed(15 DOWNTO 0) := to_signed(5127, 16); -- sfix16_En20
  CONSTANT coeff85                        : signed(15 DOWNTO 0) := to_signed(4652, 16); -- sfix16_En20
  CONSTANT coeff86                        : signed(15 DOWNTO 0) := to_signed(4203, 16); -- sfix16_En20
  CONSTANT coeff87                        : signed(15 DOWNTO 0) := to_signed(3783, 16); -- sfix16_En20
  CONSTANT coeff88                        : signed(15 DOWNTO 0) := to_signed(3391, 16); -- sfix16_En20
  CONSTANT coeff89                        : signed(15 DOWNTO 0) := to_signed(3030, 16); -- sfix16_En20
  CONSTANT coeff90                        : signed(15 DOWNTO 0) := to_signed(2700, 16); -- sfix16_En20
  CONSTANT coeff91                        : signed(15 DOWNTO 0) := to_signed(2401, 16); -- sfix16_En20
  CONSTANT coeff92                        : signed(15 DOWNTO 0) := to_signed(2133, 16); -- sfix16_En20
  CONSTANT coeff93                        : signed(15 DOWNTO 0) := to_signed(1896, 16); -- sfix16_En20
  CONSTANT coeff94                        : signed(15 DOWNTO 0) := to_signed(1690, 16); -- sfix16_En20
  CONSTANT coeff95                        : signed(15 DOWNTO 0) := to_signed(1515, 16); -- sfix16_En20
  CONSTANT coeff96                        : signed(15 DOWNTO 0) := to_signed(1370, 16); -- sfix16_En20
  CONSTANT coeff97                        : signed(15 DOWNTO 0) := to_signed(1255, 16); -- sfix16_En20
  CONSTANT coeff98                        : signed(15 DOWNTO 0) := to_signed(1168, 16); -- sfix16_En20
  CONSTANT coeff99                        : signed(15 DOWNTO 0) := to_signed(1108, 16); -- sfix16_En20
  CONSTANT coeff100                       : signed(15 DOWNTO 0) := to_signed(1074, 16); -- sfix16_En20

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 99); -- sfix16
  SIGNAL product100                       : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp                         : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product99                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_1                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product98                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_2                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product97                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_3                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product96                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_4                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product95                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_5                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product94                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_6                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product93                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_7                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product92                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_8                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product91                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_9                       : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product90                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_10                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product89                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_11                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product88                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_12                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product87                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_13                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product86                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_14                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product85                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_15                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product84                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_16                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product83                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_17                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product82                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_18                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product81                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_19                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product80                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_20                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product79                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_21                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product78                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_22                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product77                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_23                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product76                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_24                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product75                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_25                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product74                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_26                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product73                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_27                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product72                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_28                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product71                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_29                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product70                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_30                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product69                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_31                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product68                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_32                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product67                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_33                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product66                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_34                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product65                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_35                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product64                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_36                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product63                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_37                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product62                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_38                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product61                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_39                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product60                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_40                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product59                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_41                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product58                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_42                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product57                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_43                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product56                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_44                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product55                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_45                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product54                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_46                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product53                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_47                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product52                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_48                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product51                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_49                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product50                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_50                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product49                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_51                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product48                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_52                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product47                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_53                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product46                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_54                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product45                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_55                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product44                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_56                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product43                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_57                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product42                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_58                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product41                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_59                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product40                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_60                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product39                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_61                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product38                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_62                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product37                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_63                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product36                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_64                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product35                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_65                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product34                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_66                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product33                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_67                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product32                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_68                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product31                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_69                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product30                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_70                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product29                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_71                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product28                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_72                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product27                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_73                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product26                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_74                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product25                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_75                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product24                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_76                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product23                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_77                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product22                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_78                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product21                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_79                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product20                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_80                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product19                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_81                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product18                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_82                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product17                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_83                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product16                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_84                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product15                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_85                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product14                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_86                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product13                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_87                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product12                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_88                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product11                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_89                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product10                        : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_90                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product9                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_91                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product8                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_92                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product7                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_93                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product6                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_94                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product5                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_95                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product4                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_96                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product3                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_97                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product2                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_98                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL product1_cast                    : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL product1                         : signed(29 DOWNTO 0); -- sfix30_En18
  SIGNAL mul_temp_99                      : signed(31 DOWNTO 0); -- sfix32_En20
  SIGNAL sum1                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp                         : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum2                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_1                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum3                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_2                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum4                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_3                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum5                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_4                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum6                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_5                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum7                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_6                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum8                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_7                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum9                             : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_8                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum10                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_9                       : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum11                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_10                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum12                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_11                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum13                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_12                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum14                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_13                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum15                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_14                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum16                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_15                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum17                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_16                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum18                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_17                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum19                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_18                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum20                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_19                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum21                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_20                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum22                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_21                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum23                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_22                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum24                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_23                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum25                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_24                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum26                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_25                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum27                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_26                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum28                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_27                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum29                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_28                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum30                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_29                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum31                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_30                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum32                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_31                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum33                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_32                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum34                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_33                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum35                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_34                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum36                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_35                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum37                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_36                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum38                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_37                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum39                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_38                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum40                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_39                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum41                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_40                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum42                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_41                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum43                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_42                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum44                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_43                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum45                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_44                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum46                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_45                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum47                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_46                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum48                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_47                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum49                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_48                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum50                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_49                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum51                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_50                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum52                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_51                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum53                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_52                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum54                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_53                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum55                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_54                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum56                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_55                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum57                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_56                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum58                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_57                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum59                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_58                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum60                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_59                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum61                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_60                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum62                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_61                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum63                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_62                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum64                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_63                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum65                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_64                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum66                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_65                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum67                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_66                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum68                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_67                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum69                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_68                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum70                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_69                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum71                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_70                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum72                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_71                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum73                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_72                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum74                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_73                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum75                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_74                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum76                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_75                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum77                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_76                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum78                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_77                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum79                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_78                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum80                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_79                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum81                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_80                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum82                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_81                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum83                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_82                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum84                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_83                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum85                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_84                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum86                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_85                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum87                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_86                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum88                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_87                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum89                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_88                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum90                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_89                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum91                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_90                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum92                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_91                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum93                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_92                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum94                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_93                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum95                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_94                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum96                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_95                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum97                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_96                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum98                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_97                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL sum99                            : signed(33 DOWNTO 0); -- sfix34_En18
  SIGNAL add_temp_98                      : signed(34 DOWNTO 0); -- sfix35_En18
  SIGNAL output_typeconvert               : signed(31 DOWNTO 0); -- sfix32
  SIGNAL output_register                  : signed(31 DOWNTO 0); -- sfix32


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      delay_pipeline(0 TO 99) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 99) <= delay_pipeline(0 TO 98);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(99) * coeff100;
  product100 <= resize(shift_right(mul_temp(31 DOWNTO 0) + ( "0" & (mul_temp(2) & NOT mul_temp(2))), 2), 30);

  mul_temp_1 <= delay_pipeline(98) * coeff99;
  product99 <= resize(shift_right(mul_temp_1(31 DOWNTO 0) + ( "0" & (mul_temp_1(2) & NOT mul_temp_1(2))), 2), 30);

  mul_temp_2 <= delay_pipeline(97) * coeff98;
  product98 <= resize(shift_right(mul_temp_2(31 DOWNTO 0) + ( "0" & (mul_temp_2(2) & NOT mul_temp_2(2))), 2), 30);

  mul_temp_3 <= delay_pipeline(96) * coeff97;
  product97 <= resize(shift_right(mul_temp_3(31 DOWNTO 0) + ( "0" & (mul_temp_3(2) & NOT mul_temp_3(2))), 2), 30);

  mul_temp_4 <= delay_pipeline(95) * coeff96;
  product96 <= resize(shift_right(mul_temp_4(31 DOWNTO 0) + ( "0" & (mul_temp_4(2) & NOT mul_temp_4(2))), 2), 30);

  mul_temp_5 <= delay_pipeline(94) * coeff95;
  product95 <= resize(shift_right(mul_temp_5(31 DOWNTO 0) + ( "0" & (mul_temp_5(2) & NOT mul_temp_5(2))), 2), 30);

  mul_temp_6 <= delay_pipeline(93) * coeff94;
  product94 <= resize(shift_right(mul_temp_6(31 DOWNTO 0) + ( "0" & (mul_temp_6(2) & NOT mul_temp_6(2))), 2), 30);

  mul_temp_7 <= delay_pipeline(92) * coeff93;
  product93 <= resize(shift_right(mul_temp_7(31 DOWNTO 0) + ( "0" & (mul_temp_7(2) & NOT mul_temp_7(2))), 2), 30);

  mul_temp_8 <= delay_pipeline(91) * coeff92;
  product92 <= resize(shift_right(mul_temp_8(31 DOWNTO 0) + ( "0" & (mul_temp_8(2) & NOT mul_temp_8(2))), 2), 30);

  mul_temp_9 <= delay_pipeline(90) * coeff91;
  product91 <= resize(shift_right(mul_temp_9(31 DOWNTO 0) + ( "0" & (mul_temp_9(2) & NOT mul_temp_9(2))), 2), 30);

  mul_temp_10 <= delay_pipeline(89) * coeff90;
  product90 <= resize(shift_right(mul_temp_10(31 DOWNTO 0) + ( "0" & (mul_temp_10(2) & NOT mul_temp_10(2))), 2), 30);

  mul_temp_11 <= delay_pipeline(88) * coeff89;
  product89 <= resize(shift_right(mul_temp_11(31 DOWNTO 0) + ( "0" & (mul_temp_11(2) & NOT mul_temp_11(2))), 2), 30);

  mul_temp_12 <= delay_pipeline(87) * coeff88;
  product88 <= resize(shift_right(mul_temp_12(31 DOWNTO 0) + ( "0" & (mul_temp_12(2) & NOT mul_temp_12(2))), 2), 30);

  mul_temp_13 <= delay_pipeline(86) * coeff87;
  product87 <= resize(shift_right(mul_temp_13(31 DOWNTO 0) + ( "0" & (mul_temp_13(2) & NOT mul_temp_13(2))), 2), 30);

  mul_temp_14 <= delay_pipeline(85) * coeff86;
  product86 <= resize(shift_right(mul_temp_14(31 DOWNTO 0) + ( "0" & (mul_temp_14(2) & NOT mul_temp_14(2))), 2), 30);

  mul_temp_15 <= delay_pipeline(84) * coeff85;
  product85 <= resize(shift_right(mul_temp_15(31 DOWNTO 0) + ( "0" & (mul_temp_15(2) & NOT mul_temp_15(2))), 2), 30);

  mul_temp_16 <= delay_pipeline(83) * coeff84;
  product84 <= resize(shift_right(mul_temp_16(31 DOWNTO 0) + ( "0" & (mul_temp_16(2) & NOT mul_temp_16(2))), 2), 30);

  mul_temp_17 <= delay_pipeline(82) * coeff83;
  product83 <= resize(shift_right(mul_temp_17(31 DOWNTO 0) + ( "0" & (mul_temp_17(2) & NOT mul_temp_17(2))), 2), 30);

  mul_temp_18 <= delay_pipeline(81) * coeff82;
  product82 <= resize(shift_right(mul_temp_18(31 DOWNTO 0) + ( "0" & (mul_temp_18(2) & NOT mul_temp_18(2))), 2), 30);

  mul_temp_19 <= delay_pipeline(80) * coeff81;
  product81 <= resize(shift_right(mul_temp_19(31 DOWNTO 0) + ( "0" & (mul_temp_19(2) & NOT mul_temp_19(2))), 2), 30);

  mul_temp_20 <= delay_pipeline(79) * coeff80;
  product80 <= resize(shift_right(mul_temp_20(31 DOWNTO 0) + ( "0" & (mul_temp_20(2) & NOT mul_temp_20(2))), 2), 30);

  mul_temp_21 <= delay_pipeline(78) * coeff79;
  product79 <= resize(shift_right(mul_temp_21(31 DOWNTO 0) + ( "0" & (mul_temp_21(2) & NOT mul_temp_21(2))), 2), 30);

  mul_temp_22 <= delay_pipeline(77) * coeff78;
  product78 <= resize(shift_right(mul_temp_22(31 DOWNTO 0) + ( "0" & (mul_temp_22(2) & NOT mul_temp_22(2))), 2), 30);

  mul_temp_23 <= delay_pipeline(76) * coeff77;
  product77 <= resize(shift_right(mul_temp_23(31 DOWNTO 0) + ( "0" & (mul_temp_23(2) & NOT mul_temp_23(2))), 2), 30);

  mul_temp_24 <= delay_pipeline(75) * coeff76;
  product76 <= resize(shift_right(mul_temp_24(31 DOWNTO 0) + ( "0" & (mul_temp_24(2) & NOT mul_temp_24(2))), 2), 30);

  mul_temp_25 <= delay_pipeline(74) * coeff75;
  product75 <= resize(shift_right(mul_temp_25(31 DOWNTO 0) + ( "0" & (mul_temp_25(2) & NOT mul_temp_25(2))), 2), 30);

  mul_temp_26 <= delay_pipeline(73) * coeff74;
  product74 <= resize(shift_right(mul_temp_26(31 DOWNTO 0) + ( "0" & (mul_temp_26(2) & NOT mul_temp_26(2))), 2), 30);

  mul_temp_27 <= delay_pipeline(72) * coeff73;
  product73 <= resize(shift_right(mul_temp_27(31 DOWNTO 0) + ( "0" & (mul_temp_27(2) & NOT mul_temp_27(2))), 2), 30);

  mul_temp_28 <= delay_pipeline(71) * coeff72;
  product72 <= resize(shift_right(mul_temp_28(31 DOWNTO 0) + ( "0" & (mul_temp_28(2) & NOT mul_temp_28(2))), 2), 30);

  mul_temp_29 <= delay_pipeline(70) * coeff71;
  product71 <= resize(shift_right(mul_temp_29(31 DOWNTO 0) + ( "0" & (mul_temp_29(2) & NOT mul_temp_29(2))), 2), 30);

  mul_temp_30 <= delay_pipeline(69) * coeff70;
  product70 <= resize(shift_right(mul_temp_30(31 DOWNTO 0) + ( "0" & (mul_temp_30(2) & NOT mul_temp_30(2))), 2), 30);

  mul_temp_31 <= delay_pipeline(68) * coeff69;
  product69 <= resize(shift_right(mul_temp_31(31 DOWNTO 0) + ( "0" & (mul_temp_31(2) & NOT mul_temp_31(2))), 2), 30);

  mul_temp_32 <= delay_pipeline(67) * coeff68;
  product68 <= resize(shift_right(mul_temp_32(31 DOWNTO 0) + ( "0" & (mul_temp_32(2) & NOT mul_temp_32(2))), 2), 30);

  mul_temp_33 <= delay_pipeline(66) * coeff67;
  product67 <= resize(shift_right(mul_temp_33(31 DOWNTO 0) + ( "0" & (mul_temp_33(2) & NOT mul_temp_33(2))), 2), 30);

  mul_temp_34 <= delay_pipeline(65) * coeff66;
  product66 <= resize(shift_right(mul_temp_34(31 DOWNTO 0) + ( "0" & (mul_temp_34(2) & NOT mul_temp_34(2))), 2), 30);

  mul_temp_35 <= delay_pipeline(64) * coeff65;
  product65 <= resize(shift_right(mul_temp_35(31 DOWNTO 0) + ( "0" & (mul_temp_35(2) & NOT mul_temp_35(2))), 2), 30);

  mul_temp_36 <= delay_pipeline(63) * coeff64;
  product64 <= resize(shift_right(mul_temp_36(31 DOWNTO 0) + ( "0" & (mul_temp_36(2) & NOT mul_temp_36(2))), 2), 30);

  mul_temp_37 <= delay_pipeline(62) * coeff63;
  product63 <= resize(shift_right(mul_temp_37(31 DOWNTO 0) + ( "0" & (mul_temp_37(2) & NOT mul_temp_37(2))), 2), 30);

  mul_temp_38 <= delay_pipeline(61) * coeff62;
  product62 <= resize(shift_right(mul_temp_38(31 DOWNTO 0) + ( "0" & (mul_temp_38(2) & NOT mul_temp_38(2))), 2), 30);

  mul_temp_39 <= delay_pipeline(60) * coeff61;
  product61 <= resize(shift_right(mul_temp_39(31 DOWNTO 0) + ( "0" & (mul_temp_39(2) & NOT mul_temp_39(2))), 2), 30);

  mul_temp_40 <= delay_pipeline(59) * coeff60;
  product60 <= resize(shift_right(mul_temp_40(31 DOWNTO 0) + ( "0" & (mul_temp_40(2) & NOT mul_temp_40(2))), 2), 30);

  mul_temp_41 <= delay_pipeline(58) * coeff59;
  product59 <= resize(shift_right(mul_temp_41(31 DOWNTO 0) + ( "0" & (mul_temp_41(2) & NOT mul_temp_41(2))), 2), 30);

  mul_temp_42 <= delay_pipeline(57) * coeff58;
  product58 <= resize(shift_right(mul_temp_42(31 DOWNTO 0) + ( "0" & (mul_temp_42(2) & NOT mul_temp_42(2))), 2), 30);

  mul_temp_43 <= delay_pipeline(56) * coeff57;
  product57 <= resize(shift_right(mul_temp_43(31 DOWNTO 0) + ( "0" & (mul_temp_43(2) & NOT mul_temp_43(2))), 2), 30);

  mul_temp_44 <= delay_pipeline(55) * coeff56;
  product56 <= resize(shift_right(mul_temp_44(31 DOWNTO 0) + ( "0" & (mul_temp_44(2) & NOT mul_temp_44(2))), 2), 30);

  mul_temp_45 <= delay_pipeline(54) * coeff55;
  product55 <= resize(shift_right(mul_temp_45(31 DOWNTO 0) + ( "0" & (mul_temp_45(2) & NOT mul_temp_45(2))), 2), 30);

  mul_temp_46 <= delay_pipeline(53) * coeff54;
  product54 <= resize(shift_right(mul_temp_46(31 DOWNTO 0) + ( "0" & (mul_temp_46(2) & NOT mul_temp_46(2))), 2), 30);

  mul_temp_47 <= delay_pipeline(52) * coeff53;
  product53 <= resize(shift_right(mul_temp_47(31 DOWNTO 0) + ( "0" & (mul_temp_47(2) & NOT mul_temp_47(2))), 2), 30);

  mul_temp_48 <= delay_pipeline(51) * coeff52;
  product52 <= resize(shift_right(mul_temp_48(31 DOWNTO 0) + ( "0" & (mul_temp_48(2) & NOT mul_temp_48(2))), 2), 30);

  mul_temp_49 <= delay_pipeline(50) * coeff51;
  product51 <= resize(shift_right(mul_temp_49(31 DOWNTO 0) + ( "0" & (mul_temp_49(2) & NOT mul_temp_49(2))), 2), 30);

  mul_temp_50 <= delay_pipeline(49) * coeff50;
  product50 <= resize(shift_right(mul_temp_50(31 DOWNTO 0) + ( "0" & (mul_temp_50(2) & NOT mul_temp_50(2))), 2), 30);

  mul_temp_51 <= delay_pipeline(48) * coeff49;
  product49 <= resize(shift_right(mul_temp_51(31 DOWNTO 0) + ( "0" & (mul_temp_51(2) & NOT mul_temp_51(2))), 2), 30);

  mul_temp_52 <= delay_pipeline(47) * coeff48;
  product48 <= resize(shift_right(mul_temp_52(31 DOWNTO 0) + ( "0" & (mul_temp_52(2) & NOT mul_temp_52(2))), 2), 30);

  mul_temp_53 <= delay_pipeline(46) * coeff47;
  product47 <= resize(shift_right(mul_temp_53(31 DOWNTO 0) + ( "0" & (mul_temp_53(2) & NOT mul_temp_53(2))), 2), 30);

  mul_temp_54 <= delay_pipeline(45) * coeff46;
  product46 <= resize(shift_right(mul_temp_54(31 DOWNTO 0) + ( "0" & (mul_temp_54(2) & NOT mul_temp_54(2))), 2), 30);

  mul_temp_55 <= delay_pipeline(44) * coeff45;
  product45 <= resize(shift_right(mul_temp_55(31 DOWNTO 0) + ( "0" & (mul_temp_55(2) & NOT mul_temp_55(2))), 2), 30);

  mul_temp_56 <= delay_pipeline(43) * coeff44;
  product44 <= resize(shift_right(mul_temp_56(31 DOWNTO 0) + ( "0" & (mul_temp_56(2) & NOT mul_temp_56(2))), 2), 30);

  mul_temp_57 <= delay_pipeline(42) * coeff43;
  product43 <= resize(shift_right(mul_temp_57(31 DOWNTO 0) + ( "0" & (mul_temp_57(2) & NOT mul_temp_57(2))), 2), 30);

  mul_temp_58 <= delay_pipeline(41) * coeff42;
  product42 <= resize(shift_right(mul_temp_58(31 DOWNTO 0) + ( "0" & (mul_temp_58(2) & NOT mul_temp_58(2))), 2), 30);

  mul_temp_59 <= delay_pipeline(40) * coeff41;
  product41 <= resize(shift_right(mul_temp_59(31 DOWNTO 0) + ( "0" & (mul_temp_59(2) & NOT mul_temp_59(2))), 2), 30);

  mul_temp_60 <= delay_pipeline(39) * coeff40;
  product40 <= resize(shift_right(mul_temp_60(31 DOWNTO 0) + ( "0" & (mul_temp_60(2) & NOT mul_temp_60(2))), 2), 30);

  mul_temp_61 <= delay_pipeline(38) * coeff39;
  product39 <= resize(shift_right(mul_temp_61(31 DOWNTO 0) + ( "0" & (mul_temp_61(2) & NOT mul_temp_61(2))), 2), 30);

  mul_temp_62 <= delay_pipeline(37) * coeff38;
  product38 <= resize(shift_right(mul_temp_62(31 DOWNTO 0) + ( "0" & (mul_temp_62(2) & NOT mul_temp_62(2))), 2), 30);

  mul_temp_63 <= delay_pipeline(36) * coeff37;
  product37 <= resize(shift_right(mul_temp_63(31 DOWNTO 0) + ( "0" & (mul_temp_63(2) & NOT mul_temp_63(2))), 2), 30);

  mul_temp_64 <= delay_pipeline(35) * coeff36;
  product36 <= resize(shift_right(mul_temp_64(31 DOWNTO 0) + ( "0" & (mul_temp_64(2) & NOT mul_temp_64(2))), 2), 30);

  mul_temp_65 <= delay_pipeline(34) * coeff35;
  product35 <= resize(shift_right(mul_temp_65(31 DOWNTO 0) + ( "0" & (mul_temp_65(2) & NOT mul_temp_65(2))), 2), 30);

  mul_temp_66 <= delay_pipeline(33) * coeff34;
  product34 <= resize(shift_right(mul_temp_66(31 DOWNTO 0) + ( "0" & (mul_temp_66(2) & NOT mul_temp_66(2))), 2), 30);

  mul_temp_67 <= delay_pipeline(32) * coeff33;
  product33 <= resize(shift_right(mul_temp_67(31 DOWNTO 0) + ( "0" & (mul_temp_67(2) & NOT mul_temp_67(2))), 2), 30);

  mul_temp_68 <= delay_pipeline(31) * coeff32;
  product32 <= resize(shift_right(mul_temp_68(31 DOWNTO 0) + ( "0" & (mul_temp_68(2) & NOT mul_temp_68(2))), 2), 30);

  mul_temp_69 <= delay_pipeline(30) * coeff31;
  product31 <= resize(shift_right(mul_temp_69(31 DOWNTO 0) + ( "0" & (mul_temp_69(2) & NOT mul_temp_69(2))), 2), 30);

  mul_temp_70 <= delay_pipeline(29) * coeff30;
  product30 <= resize(shift_right(mul_temp_70(31 DOWNTO 0) + ( "0" & (mul_temp_70(2) & NOT mul_temp_70(2))), 2), 30);

  mul_temp_71 <= delay_pipeline(28) * coeff29;
  product29 <= resize(shift_right(mul_temp_71(31 DOWNTO 0) + ( "0" & (mul_temp_71(2) & NOT mul_temp_71(2))), 2), 30);

  mul_temp_72 <= delay_pipeline(27) * coeff28;
  product28 <= resize(shift_right(mul_temp_72(31 DOWNTO 0) + ( "0" & (mul_temp_72(2) & NOT mul_temp_72(2))), 2), 30);

  mul_temp_73 <= delay_pipeline(26) * coeff27;
  product27 <= resize(shift_right(mul_temp_73(31 DOWNTO 0) + ( "0" & (mul_temp_73(2) & NOT mul_temp_73(2))), 2), 30);

  mul_temp_74 <= delay_pipeline(25) * coeff26;
  product26 <= resize(shift_right(mul_temp_74(31 DOWNTO 0) + ( "0" & (mul_temp_74(2) & NOT mul_temp_74(2))), 2), 30);

  mul_temp_75 <= delay_pipeline(24) * coeff25;
  product25 <= resize(shift_right(mul_temp_75(31 DOWNTO 0) + ( "0" & (mul_temp_75(2) & NOT mul_temp_75(2))), 2), 30);

  mul_temp_76 <= delay_pipeline(23) * coeff24;
  product24 <= resize(shift_right(mul_temp_76(31 DOWNTO 0) + ( "0" & (mul_temp_76(2) & NOT mul_temp_76(2))), 2), 30);

  mul_temp_77 <= delay_pipeline(22) * coeff23;
  product23 <= resize(shift_right(mul_temp_77(31 DOWNTO 0) + ( "0" & (mul_temp_77(2) & NOT mul_temp_77(2))), 2), 30);

  mul_temp_78 <= delay_pipeline(21) * coeff22;
  product22 <= resize(shift_right(mul_temp_78(31 DOWNTO 0) + ( "0" & (mul_temp_78(2) & NOT mul_temp_78(2))), 2), 30);

  mul_temp_79 <= delay_pipeline(20) * coeff21;
  product21 <= resize(shift_right(mul_temp_79(31 DOWNTO 0) + ( "0" & (mul_temp_79(2) & NOT mul_temp_79(2))), 2), 30);

  mul_temp_80 <= delay_pipeline(19) * coeff20;
  product20 <= resize(shift_right(mul_temp_80(31 DOWNTO 0) + ( "0" & (mul_temp_80(2) & NOT mul_temp_80(2))), 2), 30);

  mul_temp_81 <= delay_pipeline(18) * coeff19;
  product19 <= resize(shift_right(mul_temp_81(31 DOWNTO 0) + ( "0" & (mul_temp_81(2) & NOT mul_temp_81(2))), 2), 30);

  mul_temp_82 <= delay_pipeline(17) * coeff18;
  product18 <= resize(shift_right(mul_temp_82(31 DOWNTO 0) + ( "0" & (mul_temp_82(2) & NOT mul_temp_82(2))), 2), 30);

  mul_temp_83 <= delay_pipeline(16) * coeff17;
  product17 <= resize(shift_right(mul_temp_83(31 DOWNTO 0) + ( "0" & (mul_temp_83(2) & NOT mul_temp_83(2))), 2), 30);

  mul_temp_84 <= delay_pipeline(15) * coeff16;
  product16 <= resize(shift_right(mul_temp_84(31 DOWNTO 0) + ( "0" & (mul_temp_84(2) & NOT mul_temp_84(2))), 2), 30);

  mul_temp_85 <= delay_pipeline(14) * coeff15;
  product15 <= resize(shift_right(mul_temp_85(31 DOWNTO 0) + ( "0" & (mul_temp_85(2) & NOT mul_temp_85(2))), 2), 30);

  mul_temp_86 <= delay_pipeline(13) * coeff14;
  product14 <= resize(shift_right(mul_temp_86(31 DOWNTO 0) + ( "0" & (mul_temp_86(2) & NOT mul_temp_86(2))), 2), 30);

  mul_temp_87 <= delay_pipeline(12) * coeff13;
  product13 <= resize(shift_right(mul_temp_87(31 DOWNTO 0) + ( "0" & (mul_temp_87(2) & NOT mul_temp_87(2))), 2), 30);

  mul_temp_88 <= delay_pipeline(11) * coeff12;
  product12 <= resize(shift_right(mul_temp_88(31 DOWNTO 0) + ( "0" & (mul_temp_88(2) & NOT mul_temp_88(2))), 2), 30);

  mul_temp_89 <= delay_pipeline(10) * coeff11;
  product11 <= resize(shift_right(mul_temp_89(31 DOWNTO 0) + ( "0" & (mul_temp_89(2) & NOT mul_temp_89(2))), 2), 30);

  mul_temp_90 <= delay_pipeline(9) * coeff10;
  product10 <= resize(shift_right(mul_temp_90(31 DOWNTO 0) + ( "0" & (mul_temp_90(2) & NOT mul_temp_90(2))), 2), 30);

  mul_temp_91 <= delay_pipeline(8) * coeff9;
  product9 <= resize(shift_right(mul_temp_91(31 DOWNTO 0) + ( "0" & (mul_temp_91(2) & NOT mul_temp_91(2))), 2), 30);

  mul_temp_92 <= delay_pipeline(7) * coeff8;
  product8 <= resize(shift_right(mul_temp_92(31 DOWNTO 0) + ( "0" & (mul_temp_92(2) & NOT mul_temp_92(2))), 2), 30);

  mul_temp_93 <= delay_pipeline(6) * coeff7;
  product7 <= resize(shift_right(mul_temp_93(31 DOWNTO 0) + ( "0" & (mul_temp_93(2) & NOT mul_temp_93(2))), 2), 30);

  mul_temp_94 <= delay_pipeline(5) * coeff6;
  product6 <= resize(shift_right(mul_temp_94(31 DOWNTO 0) + ( "0" & (mul_temp_94(2) & NOT mul_temp_94(2))), 2), 30);

  mul_temp_95 <= delay_pipeline(4) * coeff5;
  product5 <= resize(shift_right(mul_temp_95(31 DOWNTO 0) + ( "0" & (mul_temp_95(2) & NOT mul_temp_95(2))), 2), 30);

  mul_temp_96 <= delay_pipeline(3) * coeff4;
  product4 <= resize(shift_right(mul_temp_96(31 DOWNTO 0) + ( "0" & (mul_temp_96(2) & NOT mul_temp_96(2))), 2), 30);

  mul_temp_97 <= delay_pipeline(2) * coeff3;
  product3 <= resize(shift_right(mul_temp_97(31 DOWNTO 0) + ( "0" & (mul_temp_97(2) & NOT mul_temp_97(2))), 2), 30);

  mul_temp_98 <= delay_pipeline(1) * coeff2;
  product2 <= resize(shift_right(mul_temp_98(31 DOWNTO 0) + ( "0" & (mul_temp_98(2) & NOT mul_temp_98(2))), 2), 30);

  product1_cast <= resize(product1, 34);

  mul_temp_99 <= delay_pipeline(0) * coeff1;
  product1 <= resize(shift_right(mul_temp_99(31 DOWNTO 0) + ( "0" & (mul_temp_99(2) & NOT mul_temp_99(2))), 2), 30);

  add_temp <= resize(product1_cast, 35) + resize(product2, 35);
  sum1 <= add_temp(33 DOWNTO 0);

  add_temp_1 <= resize(sum1, 35) + resize(product3, 35);
  sum2 <= add_temp_1(33 DOWNTO 0);

  add_temp_2 <= resize(sum2, 35) + resize(product4, 35);
  sum3 <= add_temp_2(33 DOWNTO 0);

  add_temp_3 <= resize(sum3, 35) + resize(product5, 35);
  sum4 <= add_temp_3(33 DOWNTO 0);

  add_temp_4 <= resize(sum4, 35) + resize(product6, 35);
  sum5 <= add_temp_4(33 DOWNTO 0);

  add_temp_5 <= resize(sum5, 35) + resize(product7, 35);
  sum6 <= add_temp_5(33 DOWNTO 0);

  add_temp_6 <= resize(sum6, 35) + resize(product8, 35);
  sum7 <= add_temp_6(33 DOWNTO 0);

  add_temp_7 <= resize(sum7, 35) + resize(product9, 35);
  sum8 <= add_temp_7(33 DOWNTO 0);

  add_temp_8 <= resize(sum8, 35) + resize(product10, 35);
  sum9 <= add_temp_8(33 DOWNTO 0);

  add_temp_9 <= resize(sum9, 35) + resize(product11, 35);
  sum10 <= add_temp_9(33 DOWNTO 0);

  add_temp_10 <= resize(sum10, 35) + resize(product12, 35);
  sum11 <= add_temp_10(33 DOWNTO 0);

  add_temp_11 <= resize(sum11, 35) + resize(product13, 35);
  sum12 <= add_temp_11(33 DOWNTO 0);

  add_temp_12 <= resize(sum12, 35) + resize(product14, 35);
  sum13 <= add_temp_12(33 DOWNTO 0);

  add_temp_13 <= resize(sum13, 35) + resize(product15, 35);
  sum14 <= add_temp_13(33 DOWNTO 0);

  add_temp_14 <= resize(sum14, 35) + resize(product16, 35);
  sum15 <= add_temp_14(33 DOWNTO 0);

  add_temp_15 <= resize(sum15, 35) + resize(product17, 35);
  sum16 <= add_temp_15(33 DOWNTO 0);

  add_temp_16 <= resize(sum16, 35) + resize(product18, 35);
  sum17 <= add_temp_16(33 DOWNTO 0);

  add_temp_17 <= resize(sum17, 35) + resize(product19, 35);
  sum18 <= add_temp_17(33 DOWNTO 0);

  add_temp_18 <= resize(sum18, 35) + resize(product20, 35);
  sum19 <= add_temp_18(33 DOWNTO 0);

  add_temp_19 <= resize(sum19, 35) + resize(product21, 35);
  sum20 <= add_temp_19(33 DOWNTO 0);

  add_temp_20 <= resize(sum20, 35) + resize(product22, 35);
  sum21 <= add_temp_20(33 DOWNTO 0);

  add_temp_21 <= resize(sum21, 35) + resize(product23, 35);
  sum22 <= add_temp_21(33 DOWNTO 0);

  add_temp_22 <= resize(sum22, 35) + resize(product24, 35);
  sum23 <= add_temp_22(33 DOWNTO 0);

  add_temp_23 <= resize(sum23, 35) + resize(product25, 35);
  sum24 <= add_temp_23(33 DOWNTO 0);

  add_temp_24 <= resize(sum24, 35) + resize(product26, 35);
  sum25 <= add_temp_24(33 DOWNTO 0);

  add_temp_25 <= resize(sum25, 35) + resize(product27, 35);
  sum26 <= add_temp_25(33 DOWNTO 0);

  add_temp_26 <= resize(sum26, 35) + resize(product28, 35);
  sum27 <= add_temp_26(33 DOWNTO 0);

  add_temp_27 <= resize(sum27, 35) + resize(product29, 35);
  sum28 <= add_temp_27(33 DOWNTO 0);

  add_temp_28 <= resize(sum28, 35) + resize(product30, 35);
  sum29 <= add_temp_28(33 DOWNTO 0);

  add_temp_29 <= resize(sum29, 35) + resize(product31, 35);
  sum30 <= add_temp_29(33 DOWNTO 0);

  add_temp_30 <= resize(sum30, 35) + resize(product32, 35);
  sum31 <= add_temp_30(33 DOWNTO 0);

  add_temp_31 <= resize(sum31, 35) + resize(product33, 35);
  sum32 <= add_temp_31(33 DOWNTO 0);

  add_temp_32 <= resize(sum32, 35) + resize(product34, 35);
  sum33 <= add_temp_32(33 DOWNTO 0);

  add_temp_33 <= resize(sum33, 35) + resize(product35, 35);
  sum34 <= add_temp_33(33 DOWNTO 0);

  add_temp_34 <= resize(sum34, 35) + resize(product36, 35);
  sum35 <= add_temp_34(33 DOWNTO 0);

  add_temp_35 <= resize(sum35, 35) + resize(product37, 35);
  sum36 <= add_temp_35(33 DOWNTO 0);

  add_temp_36 <= resize(sum36, 35) + resize(product38, 35);
  sum37 <= add_temp_36(33 DOWNTO 0);

  add_temp_37 <= resize(sum37, 35) + resize(product39, 35);
  sum38 <= add_temp_37(33 DOWNTO 0);

  add_temp_38 <= resize(sum38, 35) + resize(product40, 35);
  sum39 <= add_temp_38(33 DOWNTO 0);

  add_temp_39 <= resize(sum39, 35) + resize(product41, 35);
  sum40 <= add_temp_39(33 DOWNTO 0);

  add_temp_40 <= resize(sum40, 35) + resize(product42, 35);
  sum41 <= add_temp_40(33 DOWNTO 0);

  add_temp_41 <= resize(sum41, 35) + resize(product43, 35);
  sum42 <= add_temp_41(33 DOWNTO 0);

  add_temp_42 <= resize(sum42, 35) + resize(product44, 35);
  sum43 <= add_temp_42(33 DOWNTO 0);

  add_temp_43 <= resize(sum43, 35) + resize(product45, 35);
  sum44 <= add_temp_43(33 DOWNTO 0);

  add_temp_44 <= resize(sum44, 35) + resize(product46, 35);
  sum45 <= add_temp_44(33 DOWNTO 0);

  add_temp_45 <= resize(sum45, 35) + resize(product47, 35);
  sum46 <= add_temp_45(33 DOWNTO 0);

  add_temp_46 <= resize(sum46, 35) + resize(product48, 35);
  sum47 <= add_temp_46(33 DOWNTO 0);

  add_temp_47 <= resize(sum47, 35) + resize(product49, 35);
  sum48 <= add_temp_47(33 DOWNTO 0);

  add_temp_48 <= resize(sum48, 35) + resize(product50, 35);
  sum49 <= add_temp_48(33 DOWNTO 0);

  add_temp_49 <= resize(sum49, 35) + resize(product51, 35);
  sum50 <= add_temp_49(33 DOWNTO 0);

  add_temp_50 <= resize(sum50, 35) + resize(product52, 35);
  sum51 <= add_temp_50(33 DOWNTO 0);

  add_temp_51 <= resize(sum51, 35) + resize(product53, 35);
  sum52 <= add_temp_51(33 DOWNTO 0);

  add_temp_52 <= resize(sum52, 35) + resize(product54, 35);
  sum53 <= add_temp_52(33 DOWNTO 0);

  add_temp_53 <= resize(sum53, 35) + resize(product55, 35);
  sum54 <= add_temp_53(33 DOWNTO 0);

  add_temp_54 <= resize(sum54, 35) + resize(product56, 35);
  sum55 <= add_temp_54(33 DOWNTO 0);

  add_temp_55 <= resize(sum55, 35) + resize(product57, 35);
  sum56 <= add_temp_55(33 DOWNTO 0);

  add_temp_56 <= resize(sum56, 35) + resize(product58, 35);
  sum57 <= add_temp_56(33 DOWNTO 0);

  add_temp_57 <= resize(sum57, 35) + resize(product59, 35);
  sum58 <= add_temp_57(33 DOWNTO 0);

  add_temp_58 <= resize(sum58, 35) + resize(product60, 35);
  sum59 <= add_temp_58(33 DOWNTO 0);

  add_temp_59 <= resize(sum59, 35) + resize(product61, 35);
  sum60 <= add_temp_59(33 DOWNTO 0);

  add_temp_60 <= resize(sum60, 35) + resize(product62, 35);
  sum61 <= add_temp_60(33 DOWNTO 0);

  add_temp_61 <= resize(sum61, 35) + resize(product63, 35);
  sum62 <= add_temp_61(33 DOWNTO 0);

  add_temp_62 <= resize(sum62, 35) + resize(product64, 35);
  sum63 <= add_temp_62(33 DOWNTO 0);

  add_temp_63 <= resize(sum63, 35) + resize(product65, 35);
  sum64 <= add_temp_63(33 DOWNTO 0);

  add_temp_64 <= resize(sum64, 35) + resize(product66, 35);
  sum65 <= add_temp_64(33 DOWNTO 0);

  add_temp_65 <= resize(sum65, 35) + resize(product67, 35);
  sum66 <= add_temp_65(33 DOWNTO 0);

  add_temp_66 <= resize(sum66, 35) + resize(product68, 35);
  sum67 <= add_temp_66(33 DOWNTO 0);

  add_temp_67 <= resize(sum67, 35) + resize(product69, 35);
  sum68 <= add_temp_67(33 DOWNTO 0);

  add_temp_68 <= resize(sum68, 35) + resize(product70, 35);
  sum69 <= add_temp_68(33 DOWNTO 0);

  add_temp_69 <= resize(sum69, 35) + resize(product71, 35);
  sum70 <= add_temp_69(33 DOWNTO 0);

  add_temp_70 <= resize(sum70, 35) + resize(product72, 35);
  sum71 <= add_temp_70(33 DOWNTO 0);

  add_temp_71 <= resize(sum71, 35) + resize(product73, 35);
  sum72 <= add_temp_71(33 DOWNTO 0);

  add_temp_72 <= resize(sum72, 35) + resize(product74, 35);
  sum73 <= add_temp_72(33 DOWNTO 0);

  add_temp_73 <= resize(sum73, 35) + resize(product75, 35);
  sum74 <= add_temp_73(33 DOWNTO 0);

  add_temp_74 <= resize(sum74, 35) + resize(product76, 35);
  sum75 <= add_temp_74(33 DOWNTO 0);

  add_temp_75 <= resize(sum75, 35) + resize(product77, 35);
  sum76 <= add_temp_75(33 DOWNTO 0);

  add_temp_76 <= resize(sum76, 35) + resize(product78, 35);
  sum77 <= add_temp_76(33 DOWNTO 0);

  add_temp_77 <= resize(sum77, 35) + resize(product79, 35);
  sum78 <= add_temp_77(33 DOWNTO 0);

  add_temp_78 <= resize(sum78, 35) + resize(product80, 35);
  sum79 <= add_temp_78(33 DOWNTO 0);

  add_temp_79 <= resize(sum79, 35) + resize(product81, 35);
  sum80 <= add_temp_79(33 DOWNTO 0);

  add_temp_80 <= resize(sum80, 35) + resize(product82, 35);
  sum81 <= add_temp_80(33 DOWNTO 0);

  add_temp_81 <= resize(sum81, 35) + resize(product83, 35);
  sum82 <= add_temp_81(33 DOWNTO 0);

  add_temp_82 <= resize(sum82, 35) + resize(product84, 35);
  sum83 <= add_temp_82(33 DOWNTO 0);

  add_temp_83 <= resize(sum83, 35) + resize(product85, 35);
  sum84 <= add_temp_83(33 DOWNTO 0);

  add_temp_84 <= resize(sum84, 35) + resize(product86, 35);
  sum85 <= add_temp_84(33 DOWNTO 0);

  add_temp_85 <= resize(sum85, 35) + resize(product87, 35);
  sum86 <= add_temp_85(33 DOWNTO 0);

  add_temp_86 <= resize(sum86, 35) + resize(product88, 35);
  sum87 <= add_temp_86(33 DOWNTO 0);

  add_temp_87 <= resize(sum87, 35) + resize(product89, 35);
  sum88 <= add_temp_87(33 DOWNTO 0);

  add_temp_88 <= resize(sum88, 35) + resize(product90, 35);
  sum89 <= add_temp_88(33 DOWNTO 0);

  add_temp_89 <= resize(sum89, 35) + resize(product91, 35);
  sum90 <= add_temp_89(33 DOWNTO 0);

  add_temp_90 <= resize(sum90, 35) + resize(product92, 35);
  sum91 <= add_temp_90(33 DOWNTO 0);

  add_temp_91 <= resize(sum91, 35) + resize(product93, 35);
  sum92 <= add_temp_91(33 DOWNTO 0);

  add_temp_92 <= resize(sum92, 35) + resize(product94, 35);
  sum93 <= add_temp_92(33 DOWNTO 0);

  add_temp_93 <= resize(sum93, 35) + resize(product95, 35);
  sum94 <= add_temp_93(33 DOWNTO 0);

  add_temp_94 <= resize(sum94, 35) + resize(product96, 35);
  sum95 <= add_temp_94(33 DOWNTO 0);

  add_temp_95 <= resize(sum95, 35) + resize(product97, 35);
  sum96 <= add_temp_95(33 DOWNTO 0);

  add_temp_96 <= resize(sum96, 35) + resize(product98, 35);
  sum97 <= add_temp_96(33 DOWNTO 0);

  add_temp_97 <= resize(sum97, 35) + resize(product99, 35);
  sum98 <= add_temp_97(33 DOWNTO 0);

  add_temp_98 <= resize(sum98, 35) + resize(product100, 35);
  sum99 <= add_temp_98(33 DOWNTO 0);

  output_typeconvert <= resize(shift_right(sum99(33) & sum99(33 DOWNTO 0) + ( "0" & (sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18) & NOT sum99(18))), 18), 32);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '0' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
